image:
  file: tools/gitpod/gitpod.Dockerfile

ports:
  - port: 6080
    protocol: "http"
    onOpen: open-browser
  - port: 5900
    onOpen: ignore

tasks:
  - command: "python -m imgui_datascience --example"
